### ISSUE TITLE
Missing glyphs?

### ISSUE THREAD

**Issue by oroboros** [Magisk-Modules-Repo/Lato-Font#1]
The colon is missing, but I'm not sure why only on my lockscreen and not elsewhere.
![screenshot_nova launcher_20181031-094244](https://user-images.githubusercontent.com/1668665/47779731-bc595400-dcf1-11e8-8fe2-91f390931c1a.png)

**Comment by alexschenider** [comment]
You can fix it using [this](http://www.mediafire.com/file/32t6q864q96s7hm/) . Please extract before. I think this dev can merge or add this file and replace the old files, because this bug...bug..and bug.

Source [xda](https://forum.xda-developers.com/android/themes/fonts-flashable-zips-t3219827)

**Comment by choukawaii** [comment]
> You can fix it using [this](http://www.mediafire.com/file/32t6q864q96s7hm/) . Please extract before. I think this dev @choukawaii can merge or add this file and replace the old files, because this bug...bug..and bug.
> 
> Source [xda](https://forum.xda-developers.com/android/themes/fonts-flashable-zips-t3219827)

Let me check.

**Comment by oroboros** [comment]
Magisk still shows v1.0 as the latest update available.

**Comment by alexschenider** [comment]
> > You can fix it using [this](http://www.mediafire.com/file/32t6q864q96s7hm/) . Please extract before. I think this dev @choukawaii can merge or add this file and replace the old files, because this bug...bug..and bug.
> > Source [xda](https://forum.xda-developers.com/android/themes/fonts-flashable-zips-t3219827)
> 
> Let me check, since it's working one mine.
> 
> Well, since I can't reproduce the problem, I tried to merge "missing" fonts that available from Lato UI. Hope it works.

Can you delete some useless fonts?
I think some fonts are not needed (checks starting from Nougat and Oreo).

Please compare by yourself : i.e Roboto-Hairline.ttf, Roboto-HairlineItalic.ttf, Roboto-Heavy.ttf, Roboto-HeavyItalic.ttf, Roboto-Semibold.ttf and Roboto-SemiboldItalic.ttf

**Comment by alexschenider** [comment]
Thank you for fixing it...it's look great and make a great again.

**Comment by choukawaii** [comment]
> > > You can fix it using [this](http://www.mediafire.com/file/32t6q864q96s7hm/) . Please extract before. I think this dev @choukawaii can merge or add this file and replace the old files, because this bug...bug..and bug.
> > > Source [xda](https://forum.xda-developers.com/android/themes/fonts-flashable-zips-t3219827)
> > 
> > 
> > Let me check, since it's working one mine.
> > Well, since I can't reproduce the problem, I tried to merge "missing" fonts that available from Lato UI. Hope it works.
> 
> Can you delete some useless fonts?
> I think some fonts are not needed (checks starting from Nougat and Oreo).
> 
> Please compare by yourself : i.e Roboto-Hairline.ttf, Roboto-HairlineItalic.ttf, Roboto-Heavy.ttf, Roboto-HeavyItalic.ttf, Roboto-Semibold.ttf and Roboto-SemiboldItalic.ttf

Well, for now, no.

**Comment by oroboros** [comment]
I updated to 1.2.2b, but still seeing the missing glyph.

**Comment by choukawaii** [comment]
> I updated to 1.2.2b, but still seeing the missing glyph.

Do you use another Magisk font module?

**Comment by alexschenider** [comment]
> I updated to 1.2.2b, but still seeing the missing glyph.

![screenshot_20181102-101100](https://user-images.githubusercontent.com/39288119/47891940-e775ac00-de87-11e8-883b-34d44e901804.png)
LineageOS-15.1-Official with Lato from OnePlus (xda-above) with not change default fonts.xml on etc, this working fine with any bug. Or maybe, i didn't facing bug.

**Comment by choukawaii** [comment]
> > I updated to 1.2.2b, but still seeing the missing glyph.
> 
> ![screenshot_20181102-101100](https://user-images.githubusercontent.com/39288119/47891940-e775ac00-de87-11e8-883b-34d44e901804.png)
> LineageOS-15.1-Official with Lato from OnePlus (xda-above) with not change default fonts.xml on etc, this working fine with any bug. Or maybe, i didn't facing bug.

It might caused by conflict with another font module. Should check installed module first for further investigation. But since it can't be reproduced in several phones, I closed this issue.

**Comment by oroboros** [comment]
> > LineageOS-15.1-Official with Lato from OnePlus (xda-above) with not change default fonts.xml on etc, this working fine with any bug. Or maybe, i didn't facing bug.
> 
> It might caused by conflict with another font module. Should check installed module first for further investigation. But since it can't be reproduced in several phones, I closed this issue.

The only related module I have is replacing emoji pack. Could this be the cause? 

I'm on NitrogenOS 8.1

**Comment by alexschenider** [comment]
> > > LineageOS-15.1-Official with Lato from OnePlus (xda-above) with not change default fonts.xml on etc, this working fine with any bug. Or maybe, i didn't facing bug.
> > 
> > 
> > It might caused by conflict with another font module. Should check installed module first for further investigation. But since it can't be reproduced in several phones, I closed this issue.
> 
> The only related module I have is replacing emoji pack. Could this be the cause?
> 
> I'm on NitrogenOS 8.1

No, emoji was replacing NotoColorEmoji.ttf
If you want, you can try and flash LatoFontOPO, and view this issue again.

**Comment by oroboros** [comment]
> > > > LineageOS-15.1-Official with Lato from OnePlus (xda-above) with not change default fonts.xml on etc, this working fine with any bug. Or maybe, i didn't facing bug.
> > > 
> > > 
> > > It might caused by conflict with another font module. Should check installed module first for further investigation. But since it can't be reproduced in several phones, I closed this issue.
> > 
> > 
> > The only related module I have is replacing emoji pack. Could this be the cause?
> > I'm on NitrogenOS 8.1
> 
> No, emoji was replacing NotoColorEmoji.ttf
> If you want, you can try and flash LatoFontOPO, and view this issue again.

Where do I find LatoFontOPO? A google search of it came up with nothing...

I'm thinking, could it be that the module doesn't substitute /system/fonts/AndroidClock.ttf? Or could it be that DroidSansFallback is missing when I go check my system fonts (which causes the colon to disappear. see: https://github.com/Magisk-Modules-Repo/pirasalbebellotafont/issues/5 )?

Dunno but the missing colon on the lock screen clock is the only bugged thing, but since I have it always in my face, it's annoying....

And thanks again for your help!
